<a href="https://colab.research.google.com/github/zsakhtar/data/blob/master/twittersentiment_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import re
import nltk
from nltk.tokenize.toktok import ToktokTokenizer

In [2]:
tweets = pd.read_csv("Tweets.csv")
tweets.head(10)

tweet_id  ...               user_timezone
0  570306133677760513  ...  Eastern Time (US & Canada)
1  570301130888122368  ...  Pacific Time (US & Canada)
2  570301083672813571  ...  Central Time (US & Canada)
3  570301031407624196  ...  Pacific Time (US & Canada)
4  570300817074462722  ...  Pacific Time (US & Canada)
5  570300767074181121  ...  Pacific Time (US & Canada)
6  570300616901320704  ...  Pacific Time (US & Canada)
7  570300248553349120  ...  Pacific Time (US & Canada)
8  570299953286942721  ...  Pacific Time (US & Canada)
9  570295459631263746  ...  Eastern Time (US & Canada)

[10 rows x 15 columns]

In [3]:
tweets.shape

(14640, 15)

In [4]:
tweets.describe().T

count          mean  ...           75%           max
tweet_id                      14640.0  5.692184e+17  ...  5.698905e+17  5.703106e+17
airline_sentiment_confidence  14640.0  9.001689e-01  ...  1.000000e+00  1.000000e+00
negativereason_confidence     10522.0  6.382983e-01  ...  1.000000e+00  1.000000e+00
retweet_count                 14640.0  8.265027e-02  ...  0.000000e+00  4.400000e+01

[4 rows x 8 columns]

In [5]:
tweets.retweet_count.max()

44

In [6]:
tweets[tweets["retweet_count"] == 44]

tweet_id  ...               user_timezone
11596  567897883875217408  ...  Eastern Time (US & Canada)

[1 rows x 15 columns]

In [7]:
tweets.dtypes

tweet_id                          int64
airline_sentiment                object
airline_sentiment_confidence    float64
negativereason                   object
negativereason_confidence       float64
airline                          object
airline_sentiment_gold           object
name                             object
negativereason_gold              object
retweet_count                     int64
text                             object
tweet_coord                      object
tweet_created                    object
tweet_location                   object
user_timezone                    object
dtype: object

In [8]:
tweets.isnull().any()

tweet_id                        False
airline_sentiment               False
airline_sentiment_confidence    False
negativereason                   True
negativereason_confidence        True
airline                         False
airline_sentiment_gold           True
name                            False
negativereason_gold              True
retweet_count                   False
text                            False
tweet_coord                      True
tweet_created                   False
tweet_location                   True
user_timezone                    True
dtype: bool

In [9]:
tweets["negativereason"]

0                           NaN
1                           NaN
2                           NaN
3                    Bad Flight
4                    Can't Tell
                  ...          
14635                       NaN
14636    Customer Service Issue
14637                       NaN
14638    Customer Service Issue
14639                       NaN
Name: negativereason, Length: 14640, dtype: object

In [10]:
tweets_nlp = tweets.copy()

In [11]:
tweets_nlp.columns

Index(['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence',
       'negativereason', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='object')

In [12]:
tweets_nlp.drop(["tweet_id", "airline_sentiment_confidence", "negativereason", "negativereason_confidence", "airline", "airline_sentiment_gold", "name", "negativereason_gold", "retweet_count", "tweet_coord", "tweet_created", "tweet_location", "user_timezone"], axis = 1, inplace = True)

In [13]:
tweets.head(5)

tweet_id  ...               user_timezone
0  570306133677760513  ...  Eastern Time (US & Canada)
1  570301130888122368  ...  Pacific Time (US & Canada)
2  570301083672813571  ...  Central Time (US & Canada)
3  570301031407624196  ...  Pacific Time (US & Canada)
4  570300817074462722  ...  Pacific Time (US & Canada)

[5 rows x 15 columns]

In [14]:
tweets_nlp.head(10)

airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...
5          negative  @VirginAmerica seriously would pay $30 a fligh...
6          positive  @VirginAmerica yes, nearly every time I fly VX...
7           neutral  @VirginAmerica Really missed a prime opportuni...
8          positive    @virginamerica Well, I didn't…but NOW I DO! :-D
9          positive  @VirginAmerica it was amazing, and arrived an ...

In [15]:
tweets_nlp.shape

(14640, 2)

# **Preprocessing**

In [16]:
processed = []
labels = tweets_nlp.iloc[:,0].values
features = tweets_nlp.iloc[:,1].values

In [17]:
labels

array(['neutral', 'positive', 'neutral', ..., 'neutral', 'negative',
       'neutral'], dtype=object)

In [18]:
features

array(['@VirginAmerica What @dhepburn said.',
       "@VirginAmerica plus you've added commercials to the experience... tacky.",
       "@VirginAmerica I didn't today... Must mean I need to take another trip!",
       ...,
       '@AmericanAir Please bring American Airlines to #BlackBerry10',
       "@AmericanAir you have my money, you change my flight, and don't answer your phones! Any other suggestions so I can make my commitment??",
       '@AmericanAir we have 8 ppl so we need 2 know how many seats are on the next flight. Plz put us on standby for 4 people on the next flight?'],
      dtype=object)

In [19]:
from bs4 import BeautifulSoup
features_stripped = []
for i in features:
    soup = BeautifulSoup(i, "html.parser")
    features_stripped.append(soup.get_text())
features_stripped

['@VirginAmerica What @dhepburn said.',
 "@VirginAmerica plus you've added commercials to the experience... tacky.",
 "@VirginAmerica I didn't today... Must mean I need to take another trip!",
 '@VirginAmerica it\'s really aggressive to blast obnoxious "entertainment" in your guests\' faces & they have little recourse',
 "@VirginAmerica and it's a really big bad thing about it",
 "@VirginAmerica seriously would pay $30 a flight for seats that didn't have this playing.\nit's really the only bad thing about flying VA",
 '@VirginAmerica yes, nearly every time I fly VX this “ear worm” won’t go away :)',
 '@VirginAmerica Really missed a prime opportunity for Men Without Hats parody, there. https://t.co/mWpG7grEZP',
 "@virginamerica Well, I didn't…but NOW I DO! :-D",
 "@VirginAmerica it was amazing, and arrived an hour early. You're too good to me.",
 '@VirginAmerica did you know that suicide is the second leading cause of death among teens 10-24',
 '@VirginAmerica I <3 pretty graphics. so m

In [20]:
from nltk.tokenize.toktok import ToktokTokenizer  

In [21]:
tokenize = ToktokTokenizer()
tokens = tokenize.tokenize(features)
print(tokens)

['[', "'", '@VirginAmerica', 'What', '@dhepburn', 'said.', "'", '"', '@VirginAmerica', 'plus', 'you', "'", 've', 'added', 'commercials', 'to', 'the', 'experience', '...', 'tacky.', '"', '"', '@VirginAmerica', 'I', 'didn', "'", 't', 'today', '...', 'Must', 'mean', 'I', 'need', 'to', 'take', 'another', 'trip', '!', '"', '...', "'", '@AmericanAir', 'Please', 'bring', 'American', 'Airlines', 'to', '#BlackBerry10', "'", '"', '@AmericanAir', 'you', 'have', 'my', 'money', ',', 'you', 'change', 'my', 'flight', ',', 'and', 'don', "'", 't', 'answer', 'your', 'phones', '!', 'Any', 'other', 'suggestions', 'so', 'I', 'can', 'make', 'my', 'commitment?', '?', '"', "'", '@AmericanAir', 'we', 'have', '8', 'ppl', 'so', 'we', 'need', '2', 'know', 'how', 'many', 'seats', 'are', 'on', 'the', 'next', 'flight.', 'Plz', 'put', 'us', 'on', 'standby', 'for', '4', 'people', 'on', 'the', 'next', 'flight?', "'", ']']


In [22]:
for sentence in range(0, len(features)):
    # Remove all the special characters
    tmp = re.sub(r'\W', ' ', str(features[sentence]))

    # remove all single characters
    tmp = re.sub(r'\s+[a-zA-Z]\s+', ' ', tmp)

    # Remove single characters from the start
    tmp = re.sub(r'\^[a-zA-Z]\s+', ' ', tmp) 

    # Substituting multiple spaces with single space
    tmp = re.sub(r'\s+', ' ', tmp, flags=re.I)

    # Removing prefixed 'b'
    tmp = re.sub(r'^b\s+', '', tmp)

    # Removing numbers
    tmp = re.sub(r'\d+', '', tmp)
    
    # Converting to Lowercase
    tmp = tmp.lower()

    processed.append(tmp)

In [23]:
processed

[' virginamerica what dhepburn said ',
 ' virginamerica plus you ve added commercials to the experience tacky ',
 ' virginamerica didn today must mean need to take another trip ',
 ' virginamerica it really aggressive to blast obnoxious entertainment in your guests faces amp they have little recourse',
 ' virginamerica and it a really big bad thing about it',
 ' virginamerica seriously would pay  flight for seats that didn have this playing it really the only bad thing about flying va',
 ' virginamerica yes nearly every time fly vx this ear worm won go away ',
 ' virginamerica really missed prime opportunity for men without hats parody there https co mwpggrezp',
 ' virginamerica well didn but now do d',
 ' virginamerica it was amazing and arrived an hour early you re too good to me ',
 ' virginamerica did you know that suicide is the second leading cause of death among teens  ',
 ' virginamerica lt  pretty graphics so much better than minimal iconography d',
 ' virginamerica this is su

Tfidf vectorization

In [24]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))
processed = vectorizer.fit_transform(processed).toarray()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [25]:
processed

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Model building and evaluating


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(processed, labels, test_size=0.3, random_state=0)

Using Random Forest to build the model

In [27]:
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [28]:
predictions = text_classifier.predict(X_test)


In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[2590  155   43]
 [ 501  361   57]
 [ 227   91  367]]
              precision    recall  f1-score   support

    negative       0.78      0.93      0.85      2788
     neutral       0.59      0.39      0.47       919
    positive       0.79      0.54      0.64       685

    accuracy                           0.76      4392
   macro avg       0.72      0.62      0.65      4392
weighted avg       0.74      0.76      0.74      4392

0.755464480874317
